package-lock.json, package.json, src/App.js, src/components/Footer.js, src/components/Header.js, src/components/MainCarousel.js, src/components/Post.js, src/components/PostList.js
1. 메인페이지 슬라이드 추가
2. 화면 크기에 따라 게시글 행 갯수 변환
3. 코드 리패토링 + 컴퍼넌트화
1. 메인페이지 슬라이드 추가
2. 화면 크기에 따라 게시글 행 갯수 변환
3. 코드 리패토링 + 컴퍼넌트화
슬라이드추가, 반응형웹
권한이 없어서 pr날려야 하는데 권한 주실수 있으실까요?
=> refactor: component,mainPage 세분화 및 슬라이드 추가

src/App.js, src/components/Header.js, src/components/Post.js, src/index.js, src/pages/MainPage.js
react-router 추가
1. react-router 추가
2. 메인페이지 추가
=> Feat: react-router 추가

package-lock.json, package.json, src/App.js, src/components/Header.js, src/pages/Login.js, src/pages/SignUp.js
1. 회원가입 형식 변경
2. 비밀번호 확인
3. 약간동의 확인
1. 회원가입 형식 변경
2. 비밀번호 확인
3. 약간동의 확인
리덕스 툴킷 설치하여 최초 실행시 npm i 해야 할것같습니다
=> Feat: 회원가입 추가

src/App.js, src/components/Modal/ModalLeave.js, src/components/Modal/ModalRevise.js, src/components/Modal/ModalUserInfo.js
(수정, 삭제, 회원탈퇴, 사용자정보) Modal 퍼블리싱
게시글 작성 완료 화면 => "삭제","수정","회원탈퇴"버튼을 눌렸을때 -> 모달창 랜더링
퍼블리싱 완료 !! 기능구현은 모달창 들어갔을때 '아니오' 버튼을 누르면 나가지게 해놨어요! 
사용자가 '예'를 눌렀을때 나중에 백 연결하고 구현을 해야 될 것 같아서 보류했습니다!
=> style : Modal 퍼블리싱

src/components/InformationEdit/UserImg.js, src/components/InformationEdit/UserStack.js, src/pages/InformationEdit.js, src/pages/MainPage.js
- 내 정보 수정 페이지 `InfomationEdit.js` 1차 퍼블리싱 입니다.
<p align="center"><img src="https://user-images.githubusercontent.com/106040138/202854777-02a3a8f5-9b7d-4fa9-ac44-7fb304d70e3f.gif"></p>
- `UserImg.js`에서 이미지 추가 기능구현 했지만 삭제 기능이 없습니다. 추후에 수정하겠습니다.
- `UserStack.js` css 수정이 필요합니다.
- 사용자의 프로필 이미지를 설정 할 수 있습니다.
- 사용자의 기술 스택을 칩으로 설정 할 수 있습니다.
=> Style : 내 정보수정 페이지 퍼블리싱

src/App.js, src/components/ReadPage/Post.css, src/components/ReadPage/PostComent.js, src/components/ReadPage/PostView.js, src/index.css
PostComent,PostView,Post.css UI
게시글 작성 완료 화면, 댓글창 UI 구현했습니다.
=> style : PostComent,PostView,Post.css UI

src/pages/Login.js, src/pages/SignUp.js, src/pages/WritePage.js
회원가입, 글작성 수정
- 회원가입 스택 부분 배열로 처리
- 글작성에서 인풋 사이즈 조정
- 로그인시 빈칸일경우 경고메세지
=> fix: 회원가입, 글작성 수정

src/components/Footer.js, src/pages/MainPage.js
-footer 부분 1차 퍼블리싱 입니다. 
- comeet을 클릭하면 메인 화면이 새로고침 됩니다.
- 개인정보처리방침, 이용약관 등 mui Link를 이용해 링크 걸어두었습니다.
- 1차 퍼블리싱이라 레이아웃을 손봐야 해요!
- footer에 기본적으로 꼭 필요한 부분만 넣어놨는데 더 추가해야할 부분 같이 의논해서 넣겠습니다!
=> style: footer

src/pages/WritePage.js
select 수정 및  취소& 글등록 버튼을 추가했습니다.
select 수정 : 하나의 메뉴 선택시 다른 부분도 동시에 변경되는 부분을 수정했습니다.
여러개의 select 를 하나의 usestate로 사용하면 좋을 것 같아 방법을 찾아보는중입니다.
=> feat: select 수정, 취소&글등록 버튼 추가

package-lock.json, package.json, src/app/store.js, src/components/PostList.js, src/store/post/post.js, src/store/post/postAPI.js
- 무한스크롤 기능 구현
- 밑으로 드래그할시 랜덤한 데이터가 추가됩니다
- 무한스크롤링
실행하기전에 npm i 하셔야합니다!
=> feat: 메인페이지 무한스크롤 기능 구현

src/pages/WritePage.js
기술 스택 메뉴 multi-seclected 기능 추가 
기술 스택을 여러개 선택할 수 있습니다.
=> feat : multi-select 기능 추가

src/App.js, src/components/PostList.js, src/components/PostPreview.js, src/components/ReadPage/PostView.js, src/store/post/post.js, src/store/post/postAPI.js
PR을 간략하게 설명해주세요!
PR의 부가적인 설명을 자세하게 해주세요!
이 PR을 통해 가능한 기능들을 설명해주세요!
=> test: 브랜치 덮어쓰기

src/App.js, src/components/PostList.js, src/components/PostPreview.js, src/components/ReadPage/PostView.js, src/pages/WritePage.js, src/store/post/post.js, src/store/post/postAPI.js
- 메인페이지에서 포스트 클릭
- 상세페이지로 이동
- 상세페이지 정보 요청
- 상세페이지 정보 받기
정보 받는부분은 아직 api가 없어서 콘솔로 찍히게 했습니다
상세페이지
=> Feat: 상세페이지 요청하기

package-lock.json, package.json, src/components/PostList.js, src/components/StackButton/StackButton.js, src/hooks/postListRefresh.js, src/pages/SignUp.js, src/store/post/post.js, src/store/user/user.js, src/store/user/userApi.js
fix: postList 로드시 버그 수정
- 현재 회원가입 버튼은 중복성 요청을 보내게됨 (테스트를위해 잠시)
- Signup.js 68번째 줄이 중복성 요청하는 코드
- store/user/userAPI 부분에 21번째가 중복성 요청 API가 담겨있습니다
=> fix: postList 로드시 버그 수정

src/components/ReadPage/PostComent.js
Coment 수정, 삭제, 등록 파트 목데이터로 axios 연동 진행중
목데이터를 통해 axios 연동 진행중입니다. 
업데이트 때마다 추후 올릴 예정입니다.
=> Feat : Coment axios 연동 진행

src/pages/Login.js, src/pages/SignUp.js, src/store/user/user.js, src/store/user/userApi.js, src/utils/setAuthToken.js, src/utils/setCookie.js
/store/user/userApi 6~30번째 줄까지가 로그인 관련api입니다
회원가입까진 되는거 확인했습니다
추가로
- 헤더 함수 추가
- 쿠키 설정함수 추가
=> feat: 로그인 구현 테스트

package-lock.json, package.json, src/app/store.js, src/components/Alert/Alert.js, src/components/MainCarousel.js, src/components/Modal/ModalUserInfo.js, src/pages/Login.js, src/pages/SignUp.js, src/store/user/user.js, src/store/user/userApi.js, src/utils/setCookie.js
1.  jwt디코드 추가
2. 로그인 구현 완료
3. 회원가입 구현 완료
4. 로그아웃 거의구현 완료(api필요)
2-1) 로그인시 발행된 AT,RT 쿠키에 자동추가, 헤더에 AT설정
4-1) 로그아웃시 가지고있는 쿠키 삭제, 헤더삭제
로그아웃시 API 추가하면 회원가입은 끝날거 같습니다
=> feat: jwt_decode추가

src/components/InformationEdit/UserImg.js, src/components/InformationEdit/UserName.js, src/components/InformationEdit/UserPassword.js, src/components/InformationEdit/UserStack.js, src/pages/InformationEdit.js
- userStack, userName 퍼블리싱 완료입니다
- 컬러나 레이아웃은 추후에 변경하겠습니다!
=> style: InfomationEdit 퍼블리싱

src/components/ReadPage/PostComent.js
Coment 덧글 조회 axios 연동 완료
특이하게 axios에서 get 받아올땐 query를 따야지 응답이 되더군욥!!
목데이터로 작업해서 Coment 작성 및 조회까지 확인 완료했습니당~.
다른 추가 변동사항 있을거 같아 계속 업데이트 할테니 머지는 추 후에 하겠습니다. ~~~~
=> feat : Coment 덧글 조회 axios 연동 완료

src/components/Header.js, src/components/InformationEdit/UserImg.js, src/components/Modal/ModalUserInfo.js, src/store/user/user.js, src/store/user/userApi.js
- 개인정보 수정 페이지 이미지 업로드 버그 수정
- 회원탈퇴 버튼 기능 추가
=> fix:개인정보수정 페이지 이미지 관련 버그 수정, feat: 회원탈퇴

src/components/InformationEdit/UserImg.js
=> delete: 개인정보수정페이지 비밀번호 수정 삭제

src/pages/MyPostList.js, src/store/post/post.js, src/store/post/postAPI.js
- 1차 코드 완성입니다.. 아직 api호출 연동 안됐어요!
=> feat: 내작성글 리스트 출력 실패

src/components/ReadPage/PostComent.js, src/components/ReadPage/PostView.js
Comment 백 데이터 렌더링 완료
comment 컴포넌트를 뺏더라구요! props로 comment 연결해서 퍼블리싱이랑 화면에 더미 데이터 뿌리는거까진 완료했어요 ~ 
더미로 하나의 데이터만 뿌리는거라 내일 전체 데이터를 뿌리는거 수정 할 예정이고
수정하고 난 뒤에는 리덕스 툴킷으로 응용까지 할 예정입니다~~
=> feat : comment 백 데이터 렌더링 완료

src/pages/MyPostList.js, src/store/post/post.js
- 내 작성글 조회 페이지에 리스트 결과 출력 했습니다!
- api 명세서에 있는 url로 데이터 요청 완료해서 작성글 데이터가 조회 가능합니다!
- 해당 url에 member_id가 필요한데 등록한 글이 실시간으로 (?) 동기화가 안돼서 데이터를 가지고 있는 membe_id=3으로 출력해놓았습니다
- ~~created_time (등록일) 데이터 가져와서 뒤에 시간부분만 짜르고 싶은데 해결해 보겠습니다!~~ 했습니다!
- member_id 실시간 업데이트해서 api요청 url 수정해야합니다!
=> feat: myPostList api연동

src/pages/MyPostList.js, src/pages/WritePage.js
PR을 간략하게 설명해주세요!
PR의 부가적인 설명을 자세하게 해주세요!
이 PR을 통해 가능한 기능들을 설명해주세요!
=> style: myPostList없을경우

src/components/ReadPage/PostComent.js, src/components/ReadPage/PostView.js
id값에 맞는 post 조회 성공
post를 클릭했을때 해당 값에 맞는 post_id를 받아와
데이터를 뿌려줍니다!
(첫 렌더링은 다 뿌려지는데 새로고침을 누를때마다 타입에러가 떠서
일단 옵셔널체이닝으로 타입에러는 막아놓고 렌더링은 가능하게 해놨어요! 
근데 너무 남용한거 같아서..ㅎ 다음 모임때 한번 왜 에러가 뜨는지 같이 찾아봐요..ㅜㅜ)
=> feat : id값에 맞는 post 조회 성공

src/components/ReadPage/PostView.js
setComment에 reponse.data.data 담아 뿌리기
=> feat : 데이터 뿌리기 완료

src/components/ReadPage/PostComent.js
=> feat : comment post 수정중

src/components/ReadPage/PostComent.js
Axios-post요청(post_id 받아오기 완료) 
member_id 데이터를 받아오는 로직만 짜면 될거같아용~~ (+content)
=> feat : axios-post요청(post_id 받아오기 완료) 

src/components/ReadPage/PostComent.js
post-content 작업 및 member_id 완료
=> feat : post-content 작업 및 member_id 완료

src/components/ReadPage/PostComent.js
Comment 추가 시 페이지 렌더링 완료
서버 연동하는것, 댓글 등록시 화면에 뿌려주는것 완료!
이후 해야할 일 리스트 입니다.
1. 댓글 등록시 페이지 재렌더링
2. 사용자 댓글 이미지 첨부하기
=> Feat : Comment 추가 시 페이지 렌더링 완료

src/components/ReadPage/PostComment.js
=> feat : 댓글 등록시 페이지 재렌더링

src/components/ReadPage/PostComent.js, src/components/ReadPage/PostView.js, src/pages/WritePage.js
Redirect-Post
게시글 작성 버튼 클릭시 => 해당 작성 글 post_id값을 받아 페이지 이동 기능 적용!
=> feat : Redirect-Post

src/components/InformationEdit/UserImg.js, src/components/ReadPage/PostView.js
- 사용자 수정페이지 프로필 이미지 원형 박스 cusor pointer로 변경
- rename: postView setComment-> setPostContents로 변경
=> style: InformationEdit style변경, rename: postView setComment-> setPostContents로 변경

src/components/ReadPage/PostComment.js, src/components/ReadPage/PostView.js
- 게시글 조회 페이지에서 작성자 프로필 이미지가 있을 경우 프로필 이미지를 불러옵니다!
=> feat: PostView 게시글 작성자 프로필 이미지 뿌리기

src/components/ReadPage/PostComment.js
=> Feat : Comment 작성시 리랜더링 완료

src/components/InformationEdit/UserImg.js, src/components/ReadPage/PostComment.js, src/components/ReadPage/PostView.js
=> Feat : 댓글 작성시 이미지 같이 불러오기 진행중

src/components/ReadPage/PostComment.js
=> 댓글 갯수 COMMENTS -> commentData 로  수정

src/App.js, src/components/PostPreview.js, src/components/ReadPage/PostComment.js, src/components/ReadPage/PostView.js, src/scrollTop.js
ScrollTop 및 PostPreview-퍼블리싱
1. post 이동 시 페이지 맨 윗 하면으로 scrollTop 적용
2. postPreview 전체 스타일 수정
=> Feat : ScrollTop 및 PostPreview-퍼블리싱

src/App.js, src/components/InformationEdit/UserImg.js, src/components/Modal/ModalUserInfo.js, src/components/PostList.js, src/components/PostPreview.js, src/components/ReadPage/PostComment.js, src/components/ReadPage/PostEdit.js, src/components/ReadPage/PostView.js, src/pages/MyPostList.js, src/pages/SignUp.js, src/pages/WritePage.js, src/store/post/post.js, src/store/post/postAPI.js
- post Edit 기능 구현 진행중
- Api 명세서 변경으로 인해 카멜 케이스 변경 진행중
- Axios url도 변경 고려 해야합니다.
=> feat : post Edit, Api 명세서 변경으로 인해 카멜 케이스 변경

src/store/user/user.js
setCookies key 카멜케이스 변경도 포함했습니다
=> fix: 로그인 user response.data 카멜케이스변경

src/pages/WritePage.js
=> fix : 게시글 등록 api 수정

src/components/InformationEdit/UserImg.js, src/components/PostPreview.js, src/components/ReadPage/Post.css, src/components/ReadPage/PostView.js
- 중복검사는 되지만,, 새로운 닉네임값을 입력 안했을 때 (공백일때) 도 요청이 보내지는 이슈가 추가되었씁니다….
- 중복시에 프론트단에서 띄워줄 alert창 컴포넌트만들어야 합니다
- UserImg 인풋값 입력시에 컴포넌트가 계속 리렌더링 됩니다..
=> feat: 사용자 닉네임 중복검사를 위한 요청 재설계

src/App.js, src/components/Header.js, src/components/InformationEdit/UserImg.js, src/components/PostList.js, src/components/PostPreview.js, src/components/ReadPage/PostComment.js, src/components/ReadPage/PostEdit.js, src/components/ReadPage/PostView.js, src/components/Table/CommonTableColumn.js, src/pages/Login.js, src/pages/MyPostList.js, src/pages/SignUp.js, src/pages/WritePage.js
Reverts Tamanegi-seoul/Co-meet#87
=> Revert "fix: 코드정리"

src/App.js, src/components/Header.js, src/components/InformationEdit/UserImg.js, src/components/PostList.js, src/components/PostPreview.js, src/components/ReadPage/PostComment.js, src/components/ReadPage/PostEdit.js, src/components/ReadPage/PostView.js, src/components/Table/CommonTableColumn.js, src/pages/Login.js, src/pages/MyPostList.js, src/pages/SignUp.js, src/pages/WritePage.js
PR을 간략하게 설명해주세요!
PR의 부가적인 설명을 자세하게 해주세요!
이 PR을 통해 가능한 기능들을 설명해주세요!
=> Revert "Revert "fix: 코드정리""

src/components/PostPreview.js, src/components/ReadPage/PostComment.js, src/components/ReadPage/PostEdit.js, src/components/ReadPage/PostView.js, src/pages/MyPostList.js, src/pages/WritePage.js, src/store/user/userApi.js
Api patch - Edit 기능 구현 및 댓글 입력시 keydown 오류 해결
1. Api patch - Edit 기능 구현
- 게시글 작성자에 맞게끔 id값 참조하여 게시글 작성자만 수정 삭제가 가능하게 변경 예정
2. post Comment 댓글 Enter 입력시 keydown event로 중복 입력 오류 해결
=> feat : Api patch - Edit 기능 구현 및 댓글 입력시 keydown 오류 해결

src/components/InformationEdit/UserImg.js, src/components/Modal/UserDelete.js, src/pages/WritePage.js, src/store/user/userApi.js
- mui dialog를 이용하여 모달창 띄운 후 탈퇴기능 구현완료
=> feat: 회원탈퇴기능

package.json
=> test: test

.vscode/settings.json, src/components/ReadPage/CommentEdit.js, src/components/ReadPage/PostComment.js, src/config.js, src/pages/WritePage.js, src/store/post/postAPI.js
Comment content 수정 및 삭제 버튼 퍼블리싱
state로 수정 on/off 기능만 구현 해놨고 서버 정상 작동되면 
api까지 붙혀 놓겠습니다~
=> style : Comment content 수정 및 삭제 버튼 퍼블리싱

src/components/Header.js, src/components/InformationEdit/UserImg.js, src/components/Modal/ModalUserInfo.js, src/components/PostPreview.js, src/pages/MainPage.js, src/pages/WritePage.js, src/store/user/user.js
Main 화면 - userImg 띄우기 및 퍼블리싱 완료했습니다.
=> feat : Main 화면 - userImg 띄우기 완료

src/components/Modal/ModalUserInfo.js, src/pages/WritePage.js
wirtePage 코드 수정 및 header user img 퍼블리싱
=> fix : wirtePage 코드 수정 및 header user img 퍼블리싱

src/components/Modal/ModalUserInfo.js
=> feat : 기본 이미지 설정

src/components/PostList.js, src/components/PostPreview.js, src/components/ReadPage/CommentEdit.js, src/components/ReadPage/CommentList.js, src/components/ReadPage/PostView.js
=> fix : comment value값 수정

src/app/store.js, src/components/PostList.js, src/components/ReadPage/CommentList.js, src/components/ReadPage/PostComment.js, src/pages/WritePage.js, src/store/post/post.js, src/store/post/postAPI.js
- 메인페이지에 모든 게시판을 로드했을시 더이상 로드요청 중지
- axios header에 토큰 사라지는 부분 수정
PR의 부가적인 설명을 자세하게 해주세요!
이 PR을 통해 가능한 기능들을 설명해주세요!
=> Fix: 메인페이지 스크롤, 토큰관리 수정

public/index.html
=> style: og tag 추가

package.json, public/index.html
docs: og image size 조절, package.json파일 수정
=> docs: og image size 조절, package.json파일 수정
